services:
  api:
    build: .
    ports:
      - "1235:1235"
    env_file:
      - ./stack.env
    container_name: hcgateway_api
    restart: always
    volumes:
      - ./api/service-account.json:/app/service-account.json

  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
    container_name: hcgateway_db
    env_file:
      - ./stack.env